language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - echo "skipping tests"

deploy:
  - provider: pypi
    user: __token__
    password:
      secure: WK0k7unenkNCgonyoIXLhaMm+F8qOQU53DFzWZ2uhorbs8uhHMZa0SzMnXoWB6oGxOapACN0s9/vU+0S5yTeAbrWd5ZbCavpEe4ayvzui/MQfIlSxZzbOKJnGy+KtufUxXnJ0GBug2bsPrOH7ecAiwUs0qgtxRee/75nkQAcrOBtZJ4B5nGRGoQ6D5Q7EwdkbrLXoqVrLldM7Vvk/Cg6c4gg3rWWKwl1jHB7AQQfC+ZQ2U7YYcdAJAvFp6UcdN7WNCT4iPaCgQ1Mk11IkBYCgM/rUc99YgrpQRdMcl+CNiSAMNDOvru0SRfc/o+o9Bjdi/H/Rk9eQOD7XCMPue72Lz7uO3skZVDgRvCWtHEP3h7++FZt2OKWVqq3WHLJKhWd+EabQlDInDG2gKF+t3kFW37xr8WXlOmlK/XOX9gybOBZOo7SghkhRhcYXFZ7PeFz4/eV+tvvcuybv/zDcu97VvXKiTe96SdCSVYssDpaQwqe2Il5lA/k1PpD9/DB5IzquQOuXDWuC1wLLzws4RBYBSfATwOZ+Nm3sF6mqz9rCN5bQSb0vqgew3vde0u9jfFGFlOLeNUD53DL8QotCqW+3k/HwiaRH9Jvn/8mt9xn6Q6lhcjw3rJnb4GRhgb7tyiqc57cacz0yC6QJ8iA585fX671hV0jl5tou4uNgSMjW4k=
    on:
      tags: true
      python: 3.6
    distributions: "sdist bdist_wheel"
    skip_existing: true
  - provider: snap
    channel: edge
    edge: true
    on:
      python: 3.6
